config/routes.rb
Rails.application.routes.draw do
  root to: 'rankings#latest'

  get '/auth/:provider/callback' => 'session#create'
  get '/auth/failure'            => 'session#create'
  get '/session/'                => 'session#index',   as: :login
  delete '/session/logout'       => 'session#destroy', as: :logout

  resources :rankings, only: [:index, :show, :destroy] do
    collection do
      get :latest
      get ':platform/:genre/:segment', action: 'transition', as: 'transition'
    end
  end

  resources :subscriptions
  resources :publications, only: [:index, :show]

  resources :genres
  resources :segments
  resources :item_codes, only: [:index, :show]
  resources :items, only: [:index, :show]
  resources :formatters
  resources :fetchers, only: [:index]
  resources :item_fetchers
  resources :ranking_fetchers

  unless Rails.env.test?
    require 'sidekiq/web'
    admin_constraint = -> (request) {
      request.session[:user_role] == 'admin'
    }
    constraints admin_constraint do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  include TimeScopes

  belongs_to :item_code
  belongs_to :ranking

  validates :item_code_id, presence: true

  delegate :genre, :genre_id, to: :ranking, allow_nil: true
  delegate :segment, :segment_id, to: :ranking, allow_nil: true

  def download_count
    download_count_min && download_count_max &&
      [download_count_min, download_count_max]
  end

  def download_count= arg
    if arg.blank?
      self.download_count_min = nil
      self.download_count_max = nil
    elsif arg.respond_to? :minmax
      self.download_count_min, self.download_count_max = arg.minmax
    else
      fail ArgumentError, 'argument does not respond to minmax'
    end
  end

  def download_count_min
    super.to_i
  end

  def download_count_max
    super.to_i
  end

  def last_item
    @last_item ||=
      ranking && ranking.last_ranking &&
      ranking.last_ranking.items.find_by(item_code_id: item_code_id)
  end

  def last_rank
    last_item.try :rank
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show]

  # GET /items
  def index
    @items = Item.page(params[:page])
  end

  # GET /items/1
  def show
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/items/_item.html.slim
tr
  td= item.title
  td= item.author
  td.text-right= number_to_currency item.price
  td.text-right
    i.fa.fa-star-o>
    = '%.1f' % item.rating
  td.text-right
    i.fa.fa-comment-o>
    = number_with_delimiter item.rating_count
  td.text-right
    i.fa.fa-download>
    - if item.download_count
      span= number_with_delimiter item.download_count_min.to_i
      span 〜
      span= number_with_delimiter item.download_count_max.to_i
  td.text-right
    i.fa.fa-clock-o>
    =l item.created_at

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Item
      th Genre
      th Segment
      th Rank
      th Title
      th Author
      th Price
      th Rating
      th Rating count
      th Download count

  tbody
    - @items.each do |item|
      tr
        td = item.item
        td = item.genre
        td = item.segment
        td = item.rank
        td = item.title
        td = item.author
        td = item.price
        td = item.rating
        td = item.rating_count
        td = item.download_count

app/views/items/show.html.slim
p#notice = notice

p
  strong Item:
  = @item.item
p
  strong Genre:
  = @item.genre
p
  strong Segment:
  = @item.segment
p
  strong Rank:
  = @item.rank
p
  strong Title:
  = @item.title
p
  strong Author:
  = @item.author
p
  strong Price:
  = @item.price
p
  strong Rating:
  = @item.rating
p
  strong Rating count:
  = @item.rating_count
p
  strong Download count:
  = @item.download_count

= link_to 'Back', items_path